---
stages:
  - build
  - localinstall

build:apk:
  stage: build
  image: cirrusci/flutter:3.7.7
  script:
    - flutter pub get
    - flutter build apk --release
  artifacts:
    paths:
      - build/app/outputs/flutter-apk/app-release.apk
    expire_in: 1 week
  tags:
    - docker

build:web:
  stage: build
  image: cirrusci/flutter:3.7.7
  script:
    - flutter pub get
    - flutter build web --release --web-renderer html
  artifacts:
    paths:
      - web
    expire_in: 1 week
  tags:
    - docker
