---
stages:
  - build

build:apk:
  stage: build
  image: vnmntn/flutter:0.1
  script:
    - cp $ENV .env
    - flutter pub get
    - flutter build apk --release
  artifacts:
    paths:
      - build/app/outputs/flutter-apk/app-release.apk
    expire_in: 1 week
  tags:
    - docker
